apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka-1
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-1
  template:
    metadata:
      labels:
        io.kompose.service: kafka-1
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://kafka-1:29092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092, PLAINTEXT_HOST://0.0.0.0:29092 # Listen on all interfaces
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 29092
              protocol: TCP
          name: kafka-1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka-1
  name: kafka-1
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
  selector:
    io.kompose.service: kafka-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka-2
  name: kafka-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-2
  template:
    metadata:
      labels:
        io.kompose.service: kafka-2
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://kafka-2:39092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092, PLAINTEXT_HOST://0.0.0.0:39092 # Listen on all interfaces
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 39092
              protocol: TCP
          name: kafka-2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka-2
  name: kafka-2
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "39092"
      port: 39092
      targetPort: 39092
  selector:
    io.kompose.service: kafka-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper-1
  name: zookeeper-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper-1
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper-1
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
              protocol: TCP
          name: zookeeper-1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper-1
  name: zookeeper-1
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper-2
  name: zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper-2
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper-2
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
              protocol: TCP
          name: zookeeper-2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper-2
  name: zookeeper-2
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper-2