apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper-1
  name: zookeeper-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper-1
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper-1
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
              protocol: TCP
          name: zookeeper-1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper-1
  name: zookeeper-1
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper-2
  name: zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper-2
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper-2
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
              protocol: TCP
          name: zookeeper-2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper-2
  name: zookeeper-2
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper-2