apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ai
  name: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai
  template:
    metadata:
      labels:
        io.kompose.service: ai
    spec:
      containers:
        - image: thezaal/5dd-breakthrough-ia:latest
          name: ai
          ports:
            - containerPort: 8080
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ai
  name: ai
spec: 
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080